### ISSUE TITLE
Mobile css friendly for the posts sections

### ISSUE THREAD

**Issue by SxMShaDoW** [aanupam23/hugo-sugoi#4]
Hi!

Love the framework.

I noticed one minor issue when using the theme on mobile. The "published" and "time to read" overlaps the white and makes it unreadable.

Do you plan on supporting that or should I try to look into it?

![image](https://user-images.githubusercontent.com/9122189/84839707-8b2ab600-aff2-11ea-9f56-524575b156a0.png)

**Comment by aanupam23** [comment]
@SxMShaDoW I will plan a fix for this, thanks for reporting :)

**Comment by aanupam23** [comment]
Fixed in latest master branch and thanks for report.
