### ISSUE TITLE
Struggling to setup GA tags

### ISSUE THREAD

**Issue by chhudson** [aanupam23/hugo-sugoi#6]
I've added my GA tracking ID to my own config.toml but it seems that GA is not picking it up...any ideas?

**Comment by chhudson** [comment]
Heads up the favicon if statement in the partial `head.html` is blocking the generation of the ga tag if it is not enabled.

**Comment by aanupam23** [comment]
@chhudson Thank you for reporting this with the fix in PR #7 
It has been merged in master :)
