### ISSUE TITLE
If the title of a blog post is too long, it pushes the date and reading time into the white (making it unreadable)

### ISSUE THREAD

**Issue by SxMShaDoW** [aanupam23/hugo-sugoi#8]
Steps to reproduce:
Create a title that is greater than 45 characters long on a new blog post

Expected result:
Title shows and published/read time also shows in the black section

Current result:
Title wraps and pushes the published/read time to the white section (making it not readable) 

Workaround:
Make a shorter title.

Note: Not picky on if it wraps, makes the font smaller for the title, making the black background css a little bigger to support a word wrap, etc. 

Example:
![image](https://user-images.githubusercontent.com/9122189/91102505-23aa6b80-e61e-11ea-9707-d533ad3a3da9.png)

**Comment by aanupam23** [comment]
@SxMShaDoW - Fixed, thanks for reporting.
